version: '3'
services:
  nginx:
    build:
      context: ./nginx
    image: gilsondev/node_nginx
    container_name: nodeapp_nginx
    entrypoint: dockerize -wait http://app:3000 -timeout 20s nginx -g "daemon off;"
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: .
    image: gilsondev/node_app
    container_name: node_app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: npm run serve
    networks:
      - node-network
    volumes:
      - /usr/src/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: node_db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge